export const initialValues = {
  transportMode: "",
  eventClassification: "",
  eventDate: new Date(),
  eventTime: "",
  weatherCondition: "",
  lugar: "",
  direccion: "",
  latitud: 0,
  longitud: 0,
  vehicles: [],
  notificationChannel: "",
  notifyingOrganism: "",
  notificationDate: new Date(),
  notificationTime: "",
  review: "",
  sourceLink: "",
  responseType: "",
  observations: "",
};
